/**
 * This file is the only source of truth for data structures in the Shadesmar domain. Changes must be synchronized with shadesmar-schema.
 */

// ─── Entities ──────────────────────────────────────────────────────────────────

export type EntityType =
  'character' | 'location' | 'spren' | 'magic' | 'order' | 'organization' | 'glossary' | 'event'

// ─── Reading position ──────────────────────────────────────────────────────

/**
 * User reading position in the Stormlight Archive series.
 *
 * - book :  1 to 5 for main books
 *           2.5 = Edgedancer (novella between WoR and Oathbringer)
 *           3.5 = Dawnshard (novella between Oathbringer and Rhythm of War)
 *           0   = lore pre-series, still visible
 * - part :  0 to 5 (0 = start of the book, before any part read)
 *
 * For novellas (book = 2.5 or 3.5), the part field is ignored. They are treated like atomic dots.
 */
export type ReadingPosition = {
  book: number
  part: number
}

// ─── Entity structures ──────────────────────────────────────────────────────

/**
 * Content section inside an entity sheet. Each section has its own independent revealed_at.
 */
export type EntitySection = {
  id: string
  revealed_at: ReadingPosition
  content: string
}

/**
 * Relationship between two entities, with its own visibility. A relationship can be hidden even if both entities are visible. The nature of the link may be a spoiler.
 */
export type EntityRelationship = {
  entity_id: string
  revealed_at: ReadingPosition
  type: string
  description: string
}

/**
 * Raw entity as it exits the JSON dataset. Always complete. Filtering is done exclusively by SpoilerFilter.
 * Never expose a RawEntity directly to the UI.
 */
export type RawEntity = {
  id: string
  type: EntityType
  name: string
  aliases: string[]
  first_revealed: ReadingPosition
  short_description: string
  sections: EntitySection[]
  relationships: EntityRelationship[]
  tags?: string[]
}

/**
 * Entity after filtering at user position. Only visible sections and relationships are present.
 */
export type FilteredEntity = Omit<RawEntity, 'sections' | 'relationships'> & {
  sections: EntitySection[]
  relationships: EntityRelationship[]
  hasContentAhead: boolean // indicates whether content exists beyond the current location. Used to display a "More content ahead..." indicator.
}

/**
 * Search result. Three possible states:
 * - entity: entity found and visible at the user's location
 * - locked: entity exists in the dataset but is out of scope (do not reveal name. Existence itself is a spoiler)
 * - unknown: entity absent from the database
 */
export type SearchResult =
  | { kind: 'entity'; entity: FilteredEntity; score: number }
  | { kind: 'locked' }
  | { kind: 'unknown' }

// ─── Dataset ──────────────────────────────────────────────────────────────────

/**
 * Full dataset as generated by the pipeline build. Each key corresponds to an EntityType.
 */
export type Dataset = {
  characters: RawEntity[]
  locations: RawEntity[]
  magic: RawEntity[]
  spren: RawEntity[]
  orders: RawEntity[]
  organizations: RawEntity[]
  glossary: RawEntity[]
  events: RawEntity[]
}

/**
 * Dataset metadata generated at build. Used to view version and detect updates.
 */
export type DatasetMeta = {
  version: string
  generated_at: string
  counts: Record<EntityType, number>
  total_entities: number
}
